stages: # 分段
  - install
  - build
  - deploy

cache: # 缓存
  paths:
    - node_modules
    - dist

install-job:
  tags:
    - vite-vue3-ts-pinia-1108
  stage: install
  script:
    - npm -v
    - npm config set registry https://registry.npm.taobao.org
    - npm install
  only:
    - master

build-job:
  tags:
    - vite-vue3-ts-pinia-1108
  stage: build
  script:
    - npm run build
  only:
    - master

deploy-job:
  tags:
    - vite-vue3-ts-pinia-1108
  stage: deploy
  script:
    - echo $USER
    - sshpass -p $PASSWORD scp -r ./dist/* $CUSTOM_USERNAME@$CUSTOM_IP:/usr/local/nginx/html/vite-vue3-ts-pinia
  only:
    - master
