stages: # 分段
  - install
  - build
  - deploy

cache: # 缓存
  paths:
    - node_modules
    - dist

install-job:
  tags:
    - roninz-admin
  stage: install
  script:
    - npm -v
    - npm config set registry https://registry.npmmirror.com
    - npm install
  only:
    - master
    - dev
    - uat

build-job:
  tags:
    - roninz-admin
  stage: build
  script:
    - npm run build:prod
  only:
    - master

deploy-job:
  tags:
    - roninz-admin
  stage: deploy
  script:
    - echo $USER
    - sshpass -p $PASSWORD scp -r ./dist/* $CUSTOM_USERNAME@$CUSTOM_IP:/usr/local/nginx/html/roninz-admin/prod
  only:
    - master

dev-build-job:
  tags:
    - roninz-admin
  stage: build
  script:
    - npm run build:dev
  only:
    - dev

dev-deploy-job:
  tags:
    - roninz-admin
  stage: deploy
  script:
    - sshpass -p $PASSWORD scp -r ./dist/* $CUSTOM_USERNAME@$CUSTOM_IP:/usr/local/nginx/html/roninz-admin/dev
  only:
    - dev

uat-build-job:
  tags:
    - roninz-admin
  stage: build
  script:
    - npm run build:uat
  only:
    - uat

uat-deploy-job:
  tags:
    - roninz-admin
  stage: deploy
  script:
    - sshpass -p $PASSWORD scp -r ./dist/* $CUSTOM_USERNAME@$CUSTOM_IP:/usr/local/nginx/html/roninz-admin/uat
  only:
    - uat
