/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppIframe: typeof import('./../src/components/common/app-iframe.vue')['default']
    AppPage: typeof import('./../src/components/common/app-page.vue')['default']
    'IconAntDesign:fullscreenExitOutlined': typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    'IconAntDesign:fullscreenOutlined': typeof import('~icons/ant-design/fullscreen-outlined')['default']
    IconEpAvatar: typeof import('~icons/ep/avatar')['default']
    IconEpExpand: typeof import('~icons/ep/expand')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    IconEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IconEpLock: typeof import('~icons/ep/lock')['default']
    IconEpMoon: typeof import('~icons/ep/moon')['default']
    IconEpSunny: typeof import('~icons/ep/sunny')['default']
    Loading: typeof import('./../src/components/loading/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeWarp: typeof import('./../src/components/common/theme-warp.vue')['default']
  }
}
